name: Terraform Modules CI

on:
  push:

jobs:
  validate:
    uses: joao-zanutto/shared-workflows/.github/workflows/tf-validate.yaml@main

  checkov:
    uses: joao-zanutto/shared-workflows/.github/workflows/tf-checkov.yaml@main
